@host=localhost:8000

GET http://{{host}}/api/v1/collections

###
GET http://{{host}}/api/v1/collections/1c901542-8e9b-4111-970e-e5d46676a1a4/count

###
DELETE http://{{host}}/api/v1/collections/laoyangshuo